### PR TITLE
fix: mise outdated --json does not return json if all tools are up-to-date

### LINKED ISSUE #4471: mise outdated --json does not return json if all tools are up-to-date
### Discussed in https://github.com/jdx/mise/discussions/4470

<div type='discussions-op-text'>

<sup>Originally posted by **hverlin** February 20, 2025</sup>
For example, install `mise` and immediately run `mise outdated --json`
```sh
> mise outdated --json
All tools are up to date
```

I would expect an empty object?

Would it be ok to make a PR for it?
https://github.com/jdx/mise/blob/0824490c14d17cd93c7d68930b514eb11635c451/src/cli/outdated.rs#L56-L70</div>

### PR DESCRIPTION
**Pull request by roele**
Fixes #4471

### CODE REVIEW

File: src/cli/outdated.rs [hunk 1]
```diff
@@ -82,6 +88,10 @@ impl Outdated {
 
     fn display_json(&self, outdated: Vec<OutdatedInfo>) -> Result<()> {
         let mut map = IndexMap::new();
+        if outdated.is_empty() {
+            miseprintln!("{}", serde_json::to_string_pretty(&map)?);
+            return Ok(());
+        }
```
Comment (jdx) [inline src/cli/outdated.rs]: if we left this out wouldn't it still do the same thing?

Comment (roele) [reply src/cli/outdated.rs]: Correct, good catch!
