### PR TITLE
fix(zig): can't install zig@master from v2024.4.6

### LINKED ISSUE #1956: Can't install `zig@master` from v2024.4.6
**Describe the bug**

```shell
❯ mise install zig@master --verbose
[DEBUG] ARGS: mise install zig@master --verbose
[DEBUG] Config {
    Config Files: [
        "~/.mise.toml",
        "~/.config/mise/config.toml",
    ],
}
[DEBUG] Toolset: dotnet-core@latest, lua@latest, luajit@latest, tig@latest, vim@latest, ruby@latest, neovim@nightly, node@20, powershell-core@7.4, python@3, zig@latest
downloading zig-linux-x86_64-master.tar.xz
[DEBUG] GET Downloading https://ziglang.org/download/master/zig-linux-x86_64-master.tar.xz to ~/.local/share/mise/downloads/zig/master/zig-linux-x86_64-master.tar.xz
[DEBUG] GET https://ziglang.org/download/master/zig-linux-x86_64-master.tar.xz
[DEBUG] starting new connection: https://ziglang.org/
[DEBUG] GET https://ziglang.org/download/master/zig-linux-x86_64-master.tar.xz 403 Forbidden
Error:
   0: HTTP status client error (403 Forbidden) for url (https://ziglang.org/download/master/zig-linux-x86_64-master.tar.xz)

Location:
   /home/mimikun/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mise-2024.4.8/src/http.rs:73

Version:
   2024.4.8 linux-x64 (2024-04-23)

Suggestion: Run with --verbose or MISE_VERBOSE=1 for more information.

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**To Reproduce**

1. Install mise and setup
2. Run `mise install zig@master` 

**Expected behavior**
Install success

**`mise doctor` output**

```text
❯ mise doctor
version: 2024.4.8 linux-x64 (2024-04-23)
activated: yes
shims_on_path: yes

build_info:
  Target: x86_64-unknown-linux-gnu
  Features: DEFAULT, NATIVE_TLS
  Built: Tue, 23 Apr 2024 10:31:55 +0000
  Rust Version: rustc 1.79.0-nightly (7f2fc33da 2024-04-22)
  Profile: release

shell:
  /usr/bin/fish
  fish, version 3.7.1

dirs:
  data: ~/.local/share/mise
  config: ~/.config/mise
  cache: ~/.cache/mise
  state: ~/.local/state/mise
  shims: ~/.local/share/mise/shims

config_files:
  ~/.config/mise/config.toml
  ~/.mise.toml

plugins:
  bun              (core)
  deno             (core)
  dotnet-core      https://github.com/emersonsoares/asdf-dotnet-core.git#4583e4b
  erlang           (core)
  go               (core)
  java             (core)
  lua              https://github.com/Stratus3D/asdf-lua.git#36fae6e
  luajit           https://github.com/smashedtoatoms/asdf-luaJIT.git#bbfe3cd
  neovim           https://github.com/richin13/asdf-neovim.git#0b7b611
  node             (core)
  powershell-core  https://github.com/mimikun/asdf-powershell-core.git#84d8930
  python           (core)
  ruby             (core)
  tig              https://github.com/koketani/asdf-tig.git#9ac08f3
  vim              https://github.com/mimikun/asdf-vim.git#5563975
  zig              (core)

toolset:
  dotnet-core@8.0.204
  lua@5.4.6
  luajit@2.0.5--2.4.4
  tig@2.5.9
  vim@9.1.0373
  ruby@3.3.1
  neovim@nightly
  node@20.12.2
  powershell-core@7.4.2
  python@3.12.3
  zig@0.12.0

env_vars:
  MISE_SHELL=fish
  MISE_FISH_AUTO_ACTIVATE=1
  MISE_EXPERIMENTAL=1
  MISE_NOT_FOUND_AUTO_INSTALL=false
  MISE_USE_VERSIONS_HOST=true
  MISE_GLOBAL_CONFIG_FILE=/home/mimikun/.config/mise/config.toml
  MISE_JOBS=4
  MISE_DATA_DIR=/home/mimikun/.local/share/mise
  MISE_CONFIG_DIR=/home/mimikun/.config/mise
  MISE_LEGACY_VERSION_FILE=1
  MISE_CACHE_DIR=/home/mimikun/.cache/mise
  MISE_LOG_FILE=/home/mimikun/.cache/mise/mise.log
  MISE_YES=1
  MISE_ASDF_COMPAT=1

settings:
  activate_aggressive = false
  all_compile = false
  always_keep_download = false
  always_keep_install = false
  asdf_compat = true
  cargo_binstall = true
  color = true
  disable_default_shorthands = false
  disable_tools = []
  experimental = true
  go_default_packages_file = "~/.default-go-packages"
  go_download_mirror = "https://dl.google.com/go"
  go_repo = "https://github.com/golang/go"
  go_set_gopath = false
  go_set_goroot = true
  go_skip_checksum = false
  jobs = 4
  legacy_version_file = true
  legacy_version_file_disable_tools = []
  node_compile = false
  not_found_auto_install = false
  paranoid = false
  plugin_autoupdate_last_check_duration = "7d"
  python_compile = false
  python_default_packages_file = "/home/mimikun/.default-python-packages"
  python_pyenv_repo = "https://github.com/pyenv/pyenv.git"
  raw = false
  trusted_config_paths = []
  quiet = false
  verbose = false
  yes = true
  ci = false
  debug = false
  trace = false
  log_level = "info"
  python_venv_auto_create = false

  [status]
  missing_tools = "if_other_versions_installed"
  show_env = false
  show_tools = false

No warnings found
No problems found
```

**Additional context**
None

### PR DESCRIPTION
**Pull request by roele**
Fixes #1956 by fetching the current version for `master` from `https://ziglang.org/download/index.json` on demand without caching (nightly build) and using the `builds` instead of `downloads` context.

cc/ @MustCodeAl

### CODE REVIEW

File: src/plugins/core/zig.rs [hunk 1]
```diff
@@ -57,14 +58,23 @@ impl ZigPlugin {
...
-    fn downlaod(&self, tv: &ToolVersion, pr: &dyn SingleReport) -> Result<PathBuf> {
-        let url = format!(
-            "https://ziglang.org/download/{}/zig-{}-{}-{}.tar.xz",
-            tv.version,
-            os(),
-            arch(),
-            tv.version
-        );
+    fn download(&self, tv: &ToolVersion, pr: &dyn SingleReport) -> Result<PathBuf> {
+        let url = if tv.version == "master" {
```
Comment (jdx) [inline src/plugins/core/zig.rs]: "master" shouldn't be a valid version, it should use `ref:master` I think to make it clear that you want to use the tip of the repo if I'm understanding what this means

Comment (roele) [reply src/plugins/core/zig.rs]: Both the website https://ziglang.org/download/ and http://mise-versions.jdx.dev/zig have a `master` version which seems to be a binary build of the tip of the repo.

Wouldn't `ref:master` imply that you compile/build a certain branch/tag locally from source?

Comment (roele) [reply src/plugins/core/zig.rs]: Other option would be to filter out `master` from the http://mise-versions.jdx.dev/zig response and not allow bleeding-edge version installations. Not sure how common it is to use this, maybe someone from the Zig community can chime in here.

Comment (jdx) [reply src/plugins/core/zig.rs]: In case you didn't know, mise-versions gets its data from listing the versions with `mise ls-remote zig` so if we change mise to remove the version it will be removed from that API as well (eventually, it runs on a cron job).

I think we probably should, @booniepepper may be able to weigh in on zig generally. I suspect it probably _is_ common since in younger languages users are more likely to adopt into bleeding edge features.

Comment (booniepepper) [reply src/plugins/core/zig.rs]: Zig folks will absolutely need/want bleeding-edge versions. People who are developing software at the tip version of Zig will need to be able to know and display the version _("master" is not accurate enough to be useful in any way. It's like buying a brand-new car: it loses tremendous value almost immediately after installation)_

"master" from the Zig project perspective is not a version, the current "master" version as of posting is `0.13.0-dev.46+3648d7df1`

I'd recommend when we're parsing `https://ziglang.org/download/index.json` we extract the version for `master`.

```
{
  "master": {
    "version": "0.13.0-dev.46+3648d7df1",
    ...
```

Longer term it may be useful to keep a list of some trailing N build versions, but that list is not available through the json file we're parsing.

Comment (jdx) [reply src/plugins/core/zig.rs]: here's my question since it probably wasn't clear from earlier conversation. By convention in mise we typically use `ref:<sha>` for when we're building from a repo, e.g.: `mise install node@ref:master`. So `mise install zig@master` doesn't follow that because "master" is not a version.

So what I'm proposing is we ignore the "master" that's coming from zig's json and instead manually allow users to install with `mise install zig@ref:master`.

There are benefits beyond just following convention, one I can think of is `mise upgrade` which will behave differently if installed as `ref:master` over a "version" like `master`. In the case of `ref:` it might always upgrade because `ref:master` one day might not be the same as `ref:master` the next, but mise would assume `master` is always the same. (note this functionality isn't actually implemented yet, but I will get to it one day, there are probably other assumptions about ref: and not ref: versions that have similar expectations.

Anyways, with all of that context, my question is whether `ref:master` actually should use this json or if it should pull down the project repo and compile from scratch if you specify `ref:master`. I can thing of arguments on both sides here.

OR maybe option #3 which would be for mise to properly deal with "loose" versions like `master` which may point to different real versions. We might be able to do this today if we treated this as an alias to `0.13.0-dev.46+3648d7df1` that we update when fetching versions.

This is all pretty nitpicky stuff that doesn't have a lot of real impact today, but I suspect they will be important decisions in the future.

Comment (roele) [reply src/plugins/core/zig.rs]: Agree that `ref:master` would make much more sense in this case. As per docs it compiles from source so that's what i would expect as of now. Having said that compiling from source always comes with lots of complexity, dependencies and dealing with possible platform specifics etc. This would clearly have lots of advantages but not sure if its worth the effort doing this for every core plugin.

I am not in favour of option 3) as we should enforce/stick to semantic versioning as much as possible.

I guess (at least for now) i would prefer a more pragmatic approach like having a `0.13.0-dev.46+3648d7df1` version in the `ls-remote` output which can be installed as binary. For this to work we might need to keep a cache of the last 5-10 `0.13.0-dev.` versions and also evict those if `0.13.0` is released and move to `0.14.0-dev.`. Installing an older `-dev.` version should still be possible even if not shown in `ls-remote` by simply checking for the version to contain `-dev.` and use as is.

Comment (jdx) [reply src/plugins/core/zig.rs]: > Agree that ref:master would make much more sense in this case. As per docs it compiles from source so that's what i would expect as of now. Having said that compiling from source always comes with lots of complexity, dependencies and dealing with possible platform specifics etc. This would clearly have lots of advantages but not sure if its worth the effort doing this for every core plugin.

This is correct, and I don't think any core plugins currently support `ref:` installs though that's definitely something I consider a gap—we should support this for all of the core plugins eventually I think.

I think in the short term all we need to do is remove `master` from `mise ls-remote` and `mise install zig@ref:master` _should_ work with this PR—though of course I haven't tested that so I can't say for sure.

Comment (roele) [reply src/plugins/core/zig.rs]: I think adding support for this might prove problematic. How would we build from source for `java` with all the various different vendor builds?

I assume you refer to changing `master` to `ref:master` to install the pre-compiled binaries?
Removing `master` from `ls-remote` might require to remove the first block as we might have a chicken-egg issue with following code (unless http://mise-versions.jdx.dev sets `MISE_USE_VERSIONS_HOST`?) 
```rust
fn fetch_remote_versions(&self) -> Result<Vec<String>> {
    // let json = HTTP_FETCH.get_text("https://ziglang.org/download/index.json")?;
    match self.core.fetch_remote_versions_from_mise() {
        Ok(Some(versions)) => return Ok(versions),
        Ok(None) => {}
        Err(e) => warn!("failed to fetch remote versions: {}", e),
    }

    let releases: Vec<GithubRelease> =
        HTTP_FETCH.json("https://api.github.com/repos/ziglang/zig/releases?per_page=100")?;
    let versions = releases
        .into_iter()
        .map(|r| r.tag_name)
        .unique()
        .sorted_by_cached_key(|s| (Versioning::new(s), s.to_string()))
        .collect();
    Ok(versions)
}
```

Comment (jdx) [reply src/plugins/core/zig.rs]: ah yeah, java would be an exception to compiling
