### PR TITLE
fix(aqua): apply override of version_prefix

### LINKED ISSUE #3684: Can't install `aqua:lycheeverse/lychee@0.18.0`
**Describe the bug**
`aqua:lycheeverse/lychee@0.18.0` can't be installed.

**To Reproduce**
Run `mise use aqua:lycheeverse/lychee@0.18.0 --trace`.

**Expected behavior**
As I updated the registry and the baked-in registry has the update, if I set the version to `0.18.0`, it should install a binary from [`lychee-v0.18.0`](https://github.com/lycheeverse/lychee/releases/tag/lychee-v0.18.0).
https://github.com/aquaproj/aqua-registry/pull/30039

**`mise doctor` output**
I set `MISE_DATA_DIR` to avoid trace logs to be huge.
```text
version: 2024.12.13 linux-x64 (c970664 2024-12-17)
activated: yes
shims_on_path: no

build_info:
  Target: x86_64-unknown-linux-gnu
  Features: DEFAULT, NATIVE_TLS, OPENSSL
  Built: Tue, 17 Dec 2024 22:05:20 +0000
  Rust Version: rustc 1.83.0 (90b35a623 2024-11-26)
  Profile: release

shell:
  /bin/bash
  GNU bash, version 5.2.21(1)-release (x86_64-pc-linux-gnu)
  Copyright (C) 2022 Free Software Foundation, Inc.
  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

  This is free software; you are free to change and redistribute it.
  There is NO WARRANTY, to the extent permitted by law.

dirs:
  cache: ~/.cache/mise
  config: ~/.config/mise
  data: ~/test/.mise
  shims: ~/test/.mise/shims
  state: ~/.local/state/mise

config_files:

backends:
  aqua
  asdf
  cargo
  core
  gem
  go
  npm
  pipx
  spm
  ubi
  vfox

plugins:

toolset:

path:
  ~/.local/bin
  /usr/local/sbin
  /usr/local/bin
  /usr/sbin
  /usr/bin
  /sbin
  /bin
  /usr/games
  /usr/local/games
  /usr/lib/wsl/lib
  /mnt/c/Windows/system32
  /mnt/c/Windows
  /mnt/c/Windows/System32/Wbem
  /mnt/c/Windows/System32/WindowsPowerShell/v1.0/
  /mnt/c/Windows/System32/OpenSSH/
  /mnt/c/Program Files/dotnet/
  /mnt/c/Program Files/Tailscale/
  /mnt/c/Program Files/Cloudflare/Cloudflare WARP/
  /mnt/c/Program Files/PowerShell/7-preview/preview
  /mnt/c/Users/risu/AppData/Local/Microsoft/WindowsApps
  /mnt/c/Users/risu/AppData/Local/JetBrains/Toolbox/scripts
  /mnt/c/Users/risu/AppData/Local/Programs/Microsoft VS Code Insiders/bin
  /snap/bin

env_vars:
  MISE_DATA_DIR=~/test/.mise
  MISE_SHELL=bash

settings:

No problems found
```

**Additional context**
```
$ mise use aqua:lycheeverse/lychee@0.18.0 --trace
TRACE  1 [src/cli/mod.rs:313] logger done
TRACE  1 [src/cli/mod.rs:314] migrate start
TRACE  1 [src/cli/mod.rs:314] migrate done
DEBUG  1 [src/cli/mod.rs:319] ARGS: mise use aqua:lycheeverse/lychee@0.18.0 --trace
TRACE  1 [src/cli/mod.rs:325] run use start
TRACE  1 [src/config/mod.rs:95] load start
TRACE  1 [src/backend/mod.rs:56] load_tools start
TRACE  1 [src/registry.rs:41] disable_backends
TRACE  1 [src/registry.rs:45] disable_backends
TRACE  1 [src/backend/mod.rs:66] load_tools core
TRACE  1 [src/backend/mod.rs:77] load_tools install_state
TRACE  1 [src/backend/mod.rs:91] load_tools done
TRACE  1 [src/config/mod.rs:97] load idiomatic_files
TRACE  1 [src/config/mod.rs:103] load config_filenames
TRACE  1 [src/config/mod.rs:105] load config_paths
TRACE  1 [src/config/mod.rs:106] config_paths: []
TRACE  1 [src/config/mod.rs:108] load config_files
TRACE  1 [src/config/mod.rs:1103] load_vars start
TRACE  1 [src/config/mod.rs:1116] load_vars done
TRACE  1 [src/config/mod.rs:1118] EnvResults
TRACE  1 [src/config/mod.rs:1086] load_aliases: 0
TRACE  1 [src/config/mod.rs:738] project_root: None
TRACE  1 [src/config/mod.rs:1098] load_plugins: 0
TRACE  1 [src/config/mod.rs:135] load build
TRACE  1 [src/config/mod.rs:138] load validate
TRACE  1 [src/config/mod.rs:141] load all aliases
TRACE  1 [src/config/mod.rs:144] load redactions
TRACE  1 [src/config/mod.rs:147] config: Config {
    Config Files: [],
}
TRACE  1 [src/config/mod.rs:154] load done
TRACE  1 [src/toolset/builder.rs:52] toolset::builder::build
DEBUG  1 [src/toolset/mod.rs:282] install_some_versions: aqua:lycheeverse/lychee@0.18.0
TRACE 20 [src/toolset/tool_version.rs:38] resolving aqua:lycheeverse/lychee@0.18.0 (use_locked_version)
TRACE 20 [src/cache.rs:129] reading ~/.cache/mise/aqua-lycheeverse-lychee/remote_versions-dacf1.msgpack.z
TRACE 20 [src/backend/mod.rs:260] aqua:lycheeverse/lychee is not installed, path: ~/test/.mise/installs/aqua-lycheeverse-lychee/0.18.0 (not installed) (incomplete)
TRACE 20 [src/backend/mod.rs:260] aqua:lycheeverse/lychee is not installed, path: ~/test/.mise/installs/aqua-lycheeverse-lychee/0.18.0 (not installed) (incomplete)
INFO  20 [src/ui/progress_report.rs:167] aqua:lycheeverse/lychee@0.18.0 install
TRACE 20 [src/file.rs:68] rm -rf ~/.cache/mise/aqua-lycheeverse-lychee/0.18.0
TRACE 20 [src/file.rs:92] rm ~/test/.mise/installs/aqua-lycheeverse-lychee/0.18.0
TRACE 20 [src/file.rs:195] mkdir -p ~/test/.mise/installs/aqua-lycheeverse-lychee/0.18.0
TRACE 20 [src/file.rs:195] mkdir -p ~/test/.mise/downloads/aqua-lycheeverse-lychee/0.18.0
TRACE 20 [src/file.rs:195] mkdir -p ~/.cache/mise/aqua-lycheeverse-lychee/0.18.0
TRACE 20 [src/aqua/aqua_registry.rs:177] reading baked-in aqua-registry for lycheeverse/lychee
DEBUG 20 [src/http.rs:66] GET https://api.github.com/repos/lycheeverse/lychee/releases/tags/v0.18.0
DEBUG 20 [/cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.12.9/src/connect.rs:500] starting new connection: https://api.github.com/
DEBUG 20 [src/http.rs:70] GET https://api.github.com/repos/lycheeverse/lychee/releases/tags/v0.18.0 404 Not Found
DEBUG 20 [src/http.rs:66] GET https://api.github.com/repos/lycheeverse/lychee/releases/tags/0.18.0
DEBUG 20 [/cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.12.9/src/connect.rs:500] starting new connection: https://api.github.com/
DEBUG 20 [src/http.rs:70] GET https://api.github.com/repos/lycheeverse/lychee/releases/tags/0.18.0 404 Not Found
TRACE 20 [src/file.rs:68] rm -rf ~/test/.mise/installs/aqua-lycheeverse-lychee/0.18.0
TRACE 20 [src/file.rs:68] rm -rf ~/test/.mise/downloads/aqua-lycheeverse-lychee/0.18.0
TRACE  1 [src/cli/mod.rs:325] run use done
Error:
   0: failed to install aqua:lycheeverse/lychee@0.18.0
   1: HTTP status client error (404 Not Found) for url (https://api.github.com/repos/lycheeverse/lychee/releases/tags/0.18.0)
   2: HTTP status client error (404 Not Found) for url (https://api.github.com/repos/lycheeverse/lychee/releases/tags/v0.18.0)

Location:
   src/http.rs:72

Version:
   2024.12.13 linux-x64 (c970664 2024-12-17)

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

### PR DESCRIPTION
**Pull request by risu729**
Partially resolves #3684.

This PR allows installing `aqua:lycheeverse/lychee@0.18.0`, but `ls-remote` still prints `lychee-v0.18.0`. Furthermore, attempting to install `aqua:lycheeverse/lychee@lychee-v0.18.0` fails.

I believe this will not affect other aqua packages, unless `version_prefix` is overridden.

### CODE REVIEW

**Comment by risu729** [comment]
With #4340 merged, `ls-remote` prints `0.18.0` and `use`/`install` installs correctly at least for `lychee`.

However, `mise use aqua:lycheeverse/lychee@lychee-v0.18.0` fails with the following error. This is not a bug but might be a breaking change.
```
Error: 
   0: failed to install aqua:lycheeverse/lychee@lychee-v0.18.0
   1: HTTP status client error (404 Not Found) for url (https://api.github.com/repos/lycheeverse/lychee/releases/tags/lychee-lychee-v0.18.0)
   2: HTTP status client error (404 Not Found) for url (https://api.github.com/repos/lycheeverse/lychee/releases/tags/lychee-vlychee-v0.18.0)
```

File: src/backend/aqua.rs [hunk 1]
```diff
@@ -61,6 +61,7 @@ impl Backend for AquaBackend {
                             warn!("[{}] aqua version filter error: {e}", self.ba);
                         }
                     }
+                    let pkg = AQUA_REGISTRY.package_with_version(&self.id, v).ok()?;
```
Comment (risu729) [inline src/backend/aqua.rs]: This resolves the registry for all versions, which could lead to performance concerns.
To mitigate this, we might make the `with_version` immutable by returning a new `AquaPackage` instance with the specified version. This approach should reduce the impact on performance.

Comment (risu729) [reply src/backend/aqua.rs]: Sorry, I didn't notice that `AquaPackage` was clonable. I refactored to clone it.
